language: node_js

cache:
  yarn: true
  directories:
    - node_modules
    - '$HOME/.cache'

before_install:
  - npm install -g yarn

install:
  - yarn --silent

script:
  - yarn run build

before_deploy:
  - pip install --user awscli

deploy:
  - provider: script
    script: ~/.local/bin/aws s3 sync public s3://hageveldexperience.nl --region=eu-west-1 --delete
    skip-cleanup: true
    on:
      branch: master

after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"